namespace: lordoftheflies
name: ansible_collection_sdlc
version: 1.0.0
readme: README.md
authors:
- László Hegedűs <laszlo.hegedus@cherubits.hu>
description: Ansible Collection for Software Development LifeCycle instrastructure.
license:
- Apache-2.0
license_file: LICENSE
dependencies: {}
repository: https://github.com/lordoftheflies/ansible-collection-sdlc
documentation: https://lordoftheflies.github.io/ansible-collection-sdlc
homepage: https://galaxy.ansible.com/lordoftheflies/ansible_collection_sdlc
issues: https://github.com/lordoftheflies/ansible-collection-sdlc/issues
tags:
  - cherubits
  - sdlc

