namespace: lordoftheflies
name: sdlc_collection
version: 1.0.0
readme: README.md
authors:
- László Hegedűs <laszlo.hegedus@cherubits.hu>
description: Software development lifecycle infrastructure playbook for Cherubits.
license:
- Apache-2.0
license_file: LICENSE
dependencies: {}
repository: https://github.com/lordoftheflies/sdlc_collection
documentation: http://portal.cherubits.hu/docs
homepage: https://github.com/lordoftheflies/sdlc_collection
issues: https://github.com/lordoftheflies/sdlc_collection/issues
tags:
  - cherubits
  - sdlc

