---
collections:
  - name: lordoftheflies.ansible_collection_freeipa
    version: '*'
    source: https://galaxy.ansible.com

roles:
  - name: lordoftheflies.common
    src: git@github.com:lordoftheflies/common_role.git
    version: master
    scm: git

  - name: lordoftheflies.nagios_role
    src: git@github.com:lordoftheflies/nagios_role.git
    version: master
    scm: git

  - name: lordoftheflies.apache2_role
    src: git@github.com:lordoftheflies/apache2_role.git
    version: master
    scm: git

  - name: lordoftheflies.java_role
    src: git@github.com:lordoftheflies/java_role.git
    version: master
    scm: git

  - name: lordoftheflies.python_role
    src: git@github.com:lordoftheflies/python_role.git
    version: master
    scm: git

  - name: lordoftheflies.nodejs_role
    src: git@github.com:lordoftheflies/nodejs_role.git
    version: master
    scm: git


  - name: lordoftheflies.gitlab_role
    src: git@github.com:lordoftheflies/gitlab_role.git
    version: master
    scm: git

  - name: lordoftheflies.jenkins_role
    src: git@github.com:lordoftheflies/jenkins_role.git
    version: master
    scm: git

  - name: lordoftheflies.nexus_role
    src: git@github.com:lordoftheflies/nexus_role.git
    version: master
    scm: git

  - name: lordoftheflies.sentry_role
    src: git@github.com:lordoftheflies/sentry_role.git
    version: master
    scm: git

  - name: lordoftheflies.prometheus_role
    src: git@github.com:lordoftheflies/prometheus_role.git
    version: master
    scm: git

