---

- name: "Setup virtual-servers ..."
  hosts: virtual_servers
  become: yes
  roles:
    - role: common
      state: present
  tags:
    - vps

- name: "Playbook to configure IPA server"
  hosts: ipaserver
  become: yes
  roles:
    - role: ipaserver
      state: present
  tags:
    - ipaserver

#- name: "Playbook to configure IPA server"
#  hosts: virtual_servers
#  become: yes
#  roles:
#    - role: common
#      state: present
#    - role: ipaserver
#      state: present
#  tags:
#    - ipa
#    - master
#    - server

#- name: "Playbook to configure IPA server"
#  hosts: virtual_servers
#  become: yes
#  roles:
#    - role: common
#      state: present
#    - role: ipaserver
#      state: present
#  tags:
#    - ipa
#    - master
#    - server

#- name: "Playbook to install IPA clients"
#  hosts: ipaclients
#  become: yes
#  roles:
#    - role: ipaclient
#      state: present
    #  collections:
    #    - lordoftheflies.ansible_collection_freeipa
    #  tasks:
    #   - import_role:
    #        name: lordoftheflies.ansible_collection_freeipa.ipaserver
    #    - lordoftheflies.ansible_collection_freeipa.ipagroup:
    #        option1: value
    #    - lordoftheflies.ansible_collection_freeipa.ipahost:
    #        option1: value
    #    - lordoftheflies.ansible_collection_freeipa.ipauser:
    #        option1: value
    #    - lordoftheflies.ansible_collection_freeipa.ipavault:
    #        option1: value
    #    - lordoftheflies.ansible_collection_freeipa.ipahostgroup:
    #        option1: value


    #    - import_role:
    #        name: ipaclient
    #    - debug:
    #        msg: "{{ lookup('lordoftheflies.ansible_collection_freeipa.lookup1', 'param1')| lordoftheflies.ansible_collection_freeipa.filter1 }}"
    #- name: "Playbook to configure IPA server"
    #  hosts: ipaserver
    #  become: yes

    ##  vars_files:
    ##    - playbook_sensitive_data.yml
    #
    #- name: "Playbook to install IPA clients"
    #  hosts: ipaclients
    #  become: yes
    #  roles:
    #    - role: ipaclient
    #      state: present

    #- name: "Network Getting Started First Playbook"
    #  connection: network_cli
    #  gather_facts: false
    #  hosts: web_servers
    #  tasks:

    #    - name: "Get config for VyOS devices"
    #      vyos_facts:
    #        gather_subset: all

    #    - name: "Display the config"
  #      debug:
  #        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

#    - name: "Update the hostname"
#      vyos_config:
#        backup: yes
#        lines:
#          - set system host-name vyos-changed

#    - name: "Get changed config for VyOS devices"
#      vyos_facts:
#        gather_subset: all

#    - name: "Display the changed config"
#      debug:
#        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

#- hosts: web_servers
#  gather_facts: True
#  gather_subset: min
#  module_defaults:
#    eos_facts:
#      gather_network_resources: interfaces
