---
- name: "Add inventory hosts ..."
  ipahost:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ host }}"
    description: "{{ hostvars[host]['description'] }}"
    state: present
  loop: "{{ query('inventory_hostnames', 'all') }}"
  loop_control:
    loop_var: host
  ignore_errors: true