---
- name: "Load Galaxy metadata roles"
  block:
    - name: "Get JSON from the codebase"
      uri:
        url: "https://raw.githubusercontent.com/lordoftheflies/{{ role_meta.name.split('.')[-1] }}/{{ role_meta.version }}/meta/main.yml"
        return_content: true
        method: GET
      register: role_meta_response
      until: role_meta_response.status == 200
    - name: "Set roles metadata facts"
      when: role_meta_response is defined
      set_fact:
        ansible_galaxy_roles_meta: "{{ (ansible_galaxy_roles_meta|default({}))|combine({ role_meta.name.replace('.', '_') : (role_meta_response.content|from_yaml) }) }}"
  rescue:
    - debug: msg="Failed to fetch galaxy metadata for '{{ role_meta.name }}'"
  always:
    - debug: var="ansible_galaxy_roles_meta.{{ role_meta.name.replace('.', '_') }}"
