---
- name: Converge
  hosts: all

  collections:
    - lordoftheflies.ansible_collection_sdlc

  tasks:

    - name: "Execute the ansible_install module."
      ansible_install:
        name: 'hello'
      register: testout

    - name: "Validate the ansible_install module's output"
      assert:
        that:
          - testout.original_message == 'hello'
          - testout.message == 'goodbye'