---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/lordoftheflies/docker-ubuntu1804-ansible
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: "../../plugins/modules"
    ANSIBLE_COLLECTIONS_PATHS: "/home/travis/build/lordoftheflies:~/.ansible/collections"
verifier:
  name: ansible
