---
#- name: "Generate report and manual"
#  hosts: localhost
#  include_task: tasks/report.yml

- name: "Install internal policy audit servers"
  hosts: ipaservers
  become: true
  roles:
    - role: lordoftheflies.ssl_role
      state: present
#    - role: lordoftheflies.virtualhost_role
#      state: present
  vars:
    ssl_role_root_domain: 'cherubits.hu'
    ssl_role_certificate_key_file: "{{ lookup('files', 'ssl/server.crt') }}"
    ssl_role_private_key_file: "{{ lookup('files', 'ssl/server.key') }}"
#    - role: ipaserver
#      state: present
#
#- name: "Install private virtual servers"
#  hosts: virtual_servers
#  ignore_errors: true
#  become: true
#  roles:
#    - role: ipaclient
#      state: present
#
#- name: "Install static web sites webservers"
#  hosts: web_servers
#  become: true
#  roles:
#    - role: ipaclient
#      state: present

#
#- name: "Install Jenkins servers"
#  hosts: jenkins_servers
#  roles:
#    - role: lordoftheflies.ssl_role
#      state: present
#    - role: lordoftheflies.virtualhost_role
#      state: present
#    - role: lordoftheflies.jenkins_role
#      state: present
#    - role: ipaclient
#      state: present
#    - role: nagiosclient
#      state: present
#
#- name: "Install SonarQube servers"
#  hosts: sonarqube_servers
#  roles:
#    - role: lordoftheflies.ssl_role
#      state: present
#    - role: lordoftheflies.virtualhost_role
#      state: present
#    - role: lordoftheflies.sonarqube_role
#      state: present
#    - role: ipaclient
#      state: present
#    - role: nagiosclient
#      state: present
#
#- name: "Install GitLab servers"
#  hosts: gitlab_servers
#  roles:
#    - role: lordoftheflies.ssl_role
#      state: present
#    - role: lordoftheflies.virtualhost_role
#      state: present
#    - role: lordoftheflies.docker_role
#      state: present
#    - role: lordoftheflies.mattermost_role
#      state: present
#    - role: lordoftheflies.registry_role
#      state: present
#    - role: lordoftheflies.gitlab_role
#      state: present
#    - role: ipaclient
#      state: present
#    - role: nagiosclient
#      state: present
#
#- name: "Install GitLab runners"
#  hosts: gitlab_runners
#  roles:
#    - role: lordoftheflies.ssl_role
#      state: present
#    - role: lordoftheflies.virtualhost_role
#      state: present
#    - role: lordoftheflies.docker_role
#      state: present
#    - role: ipaclient
#      state: present
#    - role: nagiosclient
#      state: present
#    - role: lordoftheflies.runner_role
#      state: present